server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    # Proxy API -> microsserviços
    location /api/login {
        proxy_pass http://auth-service:8000/api/login;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/register {
        proxy_pass http://auth-service:8000/api/register;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/clientes {
        proxy_pass http://clients-service:8000/api/clientes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/animais {
        proxy_pass http://animals-service:8000/api/animais;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/consultas {
        proxy_pass http://consultations-service:8000/api/consultas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/veterinarios {
        proxy_pass http://consultations-service:8000/api/veterinarios;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/vacinas {
        proxy_pass http://vaccination-service:8000/api/vacinas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/medicamentos {
        proxy_pass http://inventory-service:8000/api/medicamentos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
