# Generated by Django 5.2.15 on 2026-06-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('client_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('record_type', models.CharField(choices=[('consultation', 'Consulta'), ('vaccination', 'Vacinação'), ('surgery', 'Cirurgia'), ('exam', 'Exame'), ('medication', 'Medicação'), ('note', 'Observação')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='api.animalmodel')),
            ],
            options={
                'verbose_name': 'Histórico Médico',
                'verbose_name_plural': 'Históricos Médicos',
                'db_table': 'medical_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
