# Generated by Django 5.2.15 on 2026-06-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField(db_index=True)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('application_date', models.DateField()),
                ('next_dose_date', models.DateField(blank=True, db_index=True, null=True)),
                ('veterinarian_id', models.IntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'db_table': 'vaccines',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccineReminderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField(db_index=True)),
                ('reminder_date', models.DateField()),
                ('sent', models.BooleanField(default=False)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.vaccinemodel')),
            ],
            options={
                'verbose_name': 'Lembrete de Vacina',
                'verbose_name_plural': 'Lembretes de Vacina',
                'db_table': 'vaccine_reminders',
                'ordering': ['reminder_date'],
            },
        ),
    ]
